### ISSUE TITLE
Consult

### ISSUE THREAD

**Issue by mikx1234** [TempleRAIL/scope_nav#1]
When will this navigation code be updated? I need to learn something from your project. Thank you.

**Comment by zzuxzt** [comment]
Thanks for your interest in our work. I plan to update it in the next two weeks when I am not too busy. I will let you know when I update it.

**Comment by mikx1234** [comment]
My friend, have you been busy lately? When are you going to update the code on github?



At 2024-08-24 21:58:02, "Zhanteng Xie" ***@***.***> wrote:

Thanks for your interest in our work. I plan to update it in the next two weeks when I am not too busy. I will let you know when I update it.

**Comment by zzuxzt** [comment]
Sorry, I am traveling. I should be able to update it by next weekend.

**Comment by mikx1234** [comment]
OK. Thanks. Do you send an email to me when you update it?
















At 2024-09-07 23:45:42, "Zhanteng Xie" ***@***.***> wrote:

Sorry, I am traveling. I should be able to update it by next weekend.

**Comment by zzuxzt** [comment]
Hi, I just uploaded our navigation code, feel free to check it out.

**Comment by mikx1234** [comment]
ok, thanks. My friend



---- Replied Message ----
| From | Zhanteng ***@***.***> |
| Date | 09/15/2024 17:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TempleRAIL/scope_nav] Consult (Issue #1) |

Hi, I just uploaded our navigation code, feel free to check it out.
